language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

install:
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source

notifications:
  email: false
